export const departmentMap = [
	'Administrative',
	'Membership',
	'Concierge Services',
	'Activities',
	'Accounting',
	'Food and Beverage',
	'Private Events',
	'Member Events',
	'Inn at the League',
	'Services',
	'Banquets',
	'Marketing',
	'Human Resources',
	'Security',
	'The Union League Legacy Foundation',
	'The Union League Guard House',
	'The Union League Golf Club at Torresdale',
	'Union League National Golf Club',
	'Union League Liberty Hill',
	'The Bungalow',
]
