import league_house from '../../public/images/image-maps/league_house_large_op.png'

export const imageMaps = [
	{
		name: 'league-house',
		img: league_house,
		map: [
			{
				name: 'Meade Room',
				slug: 'meade-room',
				coords: [742, 84, 970, 163],
				shape: 'rect',
				href: '',
			},
			// {
			// 	name: 'Founders',
			// 	slug: 'founders',
			// 	coords: [475, 87, 635, 162],
			// 	shape: 'rect',
			// 	href: '',
			// },
			// {
			// 	name: 'Smoke Room',
			// 	slug: 'smoke-room',
			// 	coords: [172, 84, 223, 163],
			// 	shape: 'rect',
			// 	href: '',
			// },
			// {
			// 	name: 'Sitting Room',
			// 	slug: 'sitting-room',
			// 	coords: [171, 207, 219, 290],
			// 	shape: 'rect',
			// 	href: '',
			// },
			// {
			// 	name: 'Old Cafe',
			// 	slug: 'old-cafe',
			// 	coords: [278, 209, 322, 285],
			// 	shape: 'rect',
			// 	href: '',
			// },
			// {
			// 	name: 'Cafe Meredith',
			// 	slug: 'cafe-meredith',
			// 	coords: [336, 207, 383, 247],
			// 	shape: 'rect',
			// 	href: '',
			// },
			// {
			// 	name: '1862 by Martin Hamann',
			// 	slug: '1862',
			// 	coords: [480, 208, 634, 281],
			// 	shape: 'rect',
			// 	href: '',
			// },
			// {
			// 	name: 'Grant Room',
			// 	slug: 'grant-room',
			// 	coords: [744, 207, 971, 285],
			// 	shape: 'rect',
			// 	href: '',
			// },
			// {
			// 	name: 'Business Center',
			// 	slug: 'business-center',
			// 	coords: [334, 83, 380, 164],
			// 	shape: 'rect',
			// 	href: '',
			// },
			{
				name: 'Grant Room West',
				slug: 'grant-room-west',
				coords: [894, 208, 970, 284],
				shape: 'rect',
				href: '',
			},
			{
				name: 'Grant Room Center',
				slug: 'grant-room-center',
				coords: [813, 207, 888, 284],
				shape: 'rect',
				href: '',
			},
			{
				name: 'Grant Room East',
				slug: 'grant-room-east',
				coords: [742, 206, 807, 285],
				shape: 'rect',
				href: '',
			},
			{
				name: 'McMichael',
				slug: 'mcmichael',
				coords: [171, 532, 223, 646],
				shape: 'rect',
				href: '',
			},
			{
				name: 'Fell',
				slug: 'fell',
				coords: [233, 608, 293, 648],
				shape: 'rect',
				href: '',
			},
			{
				name: 'Binney',
				slug: 'binney',
				coords: [304, 608, 324, 649],
				shape: 'rect',
				href: '',
			},
			// {
			// 	name: 'Banquet Room',
			// 	slug: 'banquet-room',
			// 	coords: [334, 530, 379, 648],
			// 	shape: 'rect',
			// 	href: '',
			// },
			{
				name: 'Board Room',
				slug: 'board-room',
				coords: [332, 659, 380, 692],
				shape: 'rect',
				href: '',
			},
			{
				name: 'Farragut',
				slug: 'farragut',
				coords: [434, 625, 470, 686],
				shape: 'rect',
				href: '',
			},
			{
				name: 'Lincoln Hall',
				slug: 'lincoln-hall',
				coords: [476, 500, 637, 674],
				shape: 'rect',
				href: '',
			},
			{
				name: 'Sheridan',
				slug: 'sheridan',
				coords: [644, 621, 676, 686],
				shape: 'rect',
				href: '',
			},
			{
				name: 'Library Lounge',
				slug: 'library-lounge',
				coords: [777, 491, 883, 562],
				shape: 'rect',
				href: '',
			},
			{
				name: 'Lincoln Memorial',
				slug: 'lincoln-memorial',
				coords: [777, 608, 883, 682],
				shape: 'rect',
				href: '',
			},
			// {
			// 	name: 'Library',
			// 	slug: 'library',
			// 	coords: [897, 491, 966, 682],
			// 	shape: 'rect',
			// 	href: '',
			// },
		],
	},
]
